# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max's Microblog
email: max.schnur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writing about things that I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maxpower15.github.io" # the base hostname & protocol for your site
twitter_username: MaxSchnur
github_username:  MaxPower15
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      disqus: true
